# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
- master


jobs:

  - job: build_for_linux
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: Ant@1
        inputs:
          workingDirectory: ''
          buildFile: 'build.xml'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.8'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: true
          testResultsFiles: '**/TEST-*.xml'
          targets: 'configure-linux compile-linux test-linux install-linux'
      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: 'artifactsOut'
          artifactName: 'BeaEngine'
  - job: build_for_mac
    pool:
      vmImage: 'macos-latest'
    steps:
      - script: |
          #!/usr/bin/env bash
          echo 'Installing apache ant...'
          brew install ant

          echo 'Installing ant-contrib...'
          brew install ant-contrib
      - task: Ant@1
        inputs:
          workingDirectory: ''
          buildFile: 'build.xml'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.8'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: true
          testResultsFiles: '**/TEST-*.xml'
          targets: 'configure-mac compile-mac test-mac install-mac'
      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: 'artifactsOut'
          artifactName: 'BeaEngine'